replicaCount: 1

image:
  repository: cr.yandex/crpgf4au6prfo3nhoduj/app/flask-app
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: regcred

nameOverride: flask-app
fullnameOverride: flask-app

serviceAccount:
  create: true
  annotations: {}
  name: flask-app

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  externalPort: 5000
  internalPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: rwxrwxrwx.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:          
  CONTENTFUL_SPACE_ID: ""
  CONTENTFUL_ACEESS_TOKEN: ""
  CONTENTFUL_ABOUT_ENTRY_ID: ""
  CONTENTFUL_TOOLS_ENTRY_ID: ""
  CONTENTFUL_SITE_ENTRY_ID: ""

# kubectl create secret generic regcred --from-file=.dockerconfigjson=/home/mikh/.docker/config.json --type=kubernetes.io/dockerconfigjson

# kubectl get configmap -n kube-system coredns -o yaml
# kubectl apply -f coredns.yaml