name: Build
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    # env:
    #   REGISTRY_LOGIN: ${{ secrets.REGISTRY_LOGIN }}
    #   REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        # run: |
        #   docker login \
        #    --username ${REGISTRY_LOGIN} \
        #    --password ${REGISTRY_PASSWORD} \
        #    cr.yandex
      - name: Build and push
        working-directory: ./app
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: cr.yandex/crpgf4au6prfo3nhoduj/app/flask-app:latest
